name: Android Build

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'APK build type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      runnerType:
        description: 'Runner to use'
        required: true
        default: 'github'
        type: choice
        options:
          - github
          - ubuntu

jobs:
  build:
    name: Build Android APK
    runs-on: ${{ github.event.inputs.runnerType == 'ubuntu' && 'brahim4Captiva' || 'ubuntu-latest' }}
    env:
      BUILD_TYPE: ${{ github.event.inputs.buildType || 'debug' }}

    steps:
      - name: Clean physical workspace
        if: github.event.inputs.runnerType == 'ubuntu'
        run: |
          sudo rm -rf "${{ runner.workspace }}/FitnessNotes/FitnessNotes" || true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        if: github.event.inputs.runnerType != 'ubuntu'
        run: echo "${{ secrets.DOCKERHUB_TOKEN_OR_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker image
        if: github.event.inputs.runnerType != 'ubuntu'
        run: docker pull ehb2docker/react-native-android-jdk21:latest

      - name: Build in Docker (GitHub-hosted runner)
        if: github.event.inputs.runnerType != 'ubuntu'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ehb2docker/react-native-android-jdk21 /bin/bash -c "
            npm install &&
            npm run build &&
            npx @capacitor/assets generate --android &&
            npx cap add android || true &&
            npx cap sync android &&
            cd android &&
            ./gradlew assemble${BUILD_TYPE^}
          "

      - name: Build on physical Ubuntu runner
        if: github.event.inputs.runnerType == 'ubuntu'
        run: |
          cd ${{ runner.workspace }}/FitnessNotes/FitnessNotes
          rm -rf dist
          npm install
          npm run build -- --no-cache
          npx @capacitor/assets generate --android
          npx cap add android || true
          npx cap sync android
          cd android
          ./gradlew assemble${BUILD_TYPE^}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ env.BUILD_TYPE }}.apk
          path: android/app/build/outputs/apk/${{ env.BUILD_TYPE }}/app-*.apk
