name: Android Build

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Select APK build type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: ${{ github.event.inputs.buildType || 'debug' }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker Login to pull private image
      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN_OR_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Pull your Docker image from Docker Hub
      - name: Pull Docker image
        run: |
          docker pull ehb2docker/react-native-android-jdk21:latest

      - name: Run build inside Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ehb2docker/react-native-android-jdk21 /bin/bash -c "
            npm install &&
            npm run build &&
            npx @capacitor/assets generate --android &&
            npx cap add android || true &&
            npx cap sync android &&
            cd android &&
            ./gradlew assemble${BUILD_TYPE^}
          "

      # Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${BUILD_TYPE^}.apk
          path: android/app/build/outputs/apk/${BUILD_TYPE^}/app-${BUILD_TYPE^}*.apk
