name: Android Build

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # OPTIONAL: Docker Login (if you want to pull base image or push your image)
      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN_OR_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Build your Docker image locally in GitHub Actions
      - name: Build Docker image
        run: |
          docker build -t ehb2docker/react-native-android-jdk21 .

      # OPTIONAL: Push your image to DockerHub (if you want to version and store it)
      - name: Push Docker image
        run: |
          docker push ehb2docker/react-native-android-jdk21

      # Run Angular + Capacitor + Gradle build inside your Docker image
      - name: Run build inside Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ehb2docker/react-native-android-jdk21 /bin/bash -c "
            npm install &&
            npm run build &&
            npx cap sync android &&
            cd android &&
            ./gradlew assembleDebug
          "

      # Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
